### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [erikcc02/radius-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by erikcc02** [comment]
@unixorn First of all thank you very much for the feedback.

I added the license here: https://github.com/erikcc02/radius-zsh-theme/commit/06f5404766d3e830e4845b052e18c68b6e287430

Feel free to share this 👍🏼 

Thanks!
